import { Info } from 'lucide-react';
import { Badge } from '../ui/badge';
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from '../ui/tooltip';

interface AIBadgeProps {
  className?: string;
  showTooltip?: boolean;
  model?: string;
}

export function AIBadge({ className, showTooltip = true, model = "OpenAI GPT-4" }: AIBadgeProps) {
  const badge = (
    <Badge variant="secondary" className={`gap-1 ${className}`}>
      AI-suggested
      {showTooltip && <Info className="h-3 w-3" />}
    </Badge>
  );

  if (!showTooltip) {
    return badge;
  }

  return (
    <TooltipProvider>
      <Tooltip>
        <TooltipTrigger asChild>
          {badge}
        </TooltipTrigger>
        <TooltipContent>
          <p>Generated by {model}</p>
        </TooltipContent>
      </Tooltip>
    </TooltipProvider>
  );
}